### ISSUE TITLE
Live Environment Doesn't Load Authorized Emails / Other Methods 

### ISSUE THREAD

**Issue by NPPerkins** [lukesUbuntu/gogetsslv2#1]
I've conducted some tests using the Sandbox Environment, and it loads the Approved Email aliases and the Other Verification options quick and fast. When switched to a Live Environment I attempted to place an order for both a RapidSSL Certificate and RapidSSL Trial (both which worked in Sandbox) but they seem to not be able to load the Approved Email aliases nor the Other Verification options.

https://www.dropbox.com/s/irqxnzov9gjo75p/Screenshot%202015-03-24%2020.06.21.png?dl=0

If you'd need a login to test this, I'll be glad to provide a login. Along with

**Comment by lukesUbuntu** [comment]
was it two different domains you applied the certs for or did you apply 1 x RapidSSL Certificate & 1 x  RapidSSL Trial to the same domain. Just trying to replicate the issue.

**Comment by NPPerkins** [comment]
Hey Luke,

It was two domains and each one was attempted for both the paid product (RapidSSL Certificate) and the free product (RapidSSL Trial).

**Comment by NPPerkins** [comment]
Hey Luke,

I've tested this on a new fresh install, and can confirm the same thing. You can test it at  http://*********/index.php/ (PHP5.5)

**Comment by lukesUbuntu** [comment]
@NPPerkins 

edit : managed to reproduce this issue thanks will resolve.

**Comment by lukesUbuntu** [comment]
Resolved issue thanks, will push shortly.
